# Site settings
title: Авто Майстер - Професійна консультація та ремонт автомобілів
description: "Oтримання професійної консультації фахівця при ремонті автомобіля. Вас обслуговує найкращий фахівець — досвідчений, кваліфікований і відповідальний працівник, який постійно проходить навчання та курси підвищення кваліфікації, відвідує тренінги, семінари, займається самоосвітою, постійно слідкує за новинками техніки"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://autoguru.pp.ua" # the name of your domain

destination: ./_site
permalink: /:title
paginate: 7
paginate_path: /page:num/

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - README.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - orig.tar.xz
  - /.git

# Custom variables

# Google Analytics
google_analytics: UA-118776377-1 # replace with your GA tracking identifier

# Contact info
contact:
    phone: +38 (098) 78 - 22 - 475
    phonecall: +380987822475
    email: andreford22111985@gmail.com
    address: Україна, м.Конотоп

# Map
map:
    zoom: 15
    address: Україна, м.Конотоп
    x: 33.2050521
    y: 51.2409432

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:beregok

# Footer
copyright:  Авто Майстер. Професійна консультація

#Compress htnl
compress_html:
  compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [head, body]
